### ISSUE TITLE
Specifying storage class

### ISSUE THREAD

**Issue by weistonedawei** [geerlingguy/mariadb-operator#11]
Hi,

This is a question.  Apologize in advance if it is inappropriate. 

I see that storage size is provided through mariadb_pvc_storage_request, how about storage class?

My usage case requires the pvc be provisioned from a non-default storage class.  If I were to edit roles/mariadb/templates/mariadb_statefulset.yaml.j2, how are the changes reflected when 'kubectl apply -f my-database.yml' is executed?

Thanks,

**Comment by geerlingguy** [comment]
If you change that in the statefulset managed by this operator, it will get overwritten by the operator on the next run. It is definitely something that should be configurable, though! Especially for databases, most people would do well to not use the default (often gp2 or something else fairly slow) storage class.

**Comment by geerlingguy** [comment]
And to make it configurable, I could add `storageClassName: "{{ mariadb_storage_class }}"` in https://github.com/geerlingguy/mariadb-operator/blob/master/roles/mariadb/templates/mariadb_statefulset.yaml.j2 in `spec. volumeClaimTemplates[0].spec`. Then set `mariadb_storage_class: default`, I think?

**Comment by weistonedawei** [comment]
Thanks for your help!
