### ISSUE TITLE
The project is still alive ?

### ISSUE THREAD

**Issue by thierrystiegler** [geerlingguy/mariadb-operator#8]
Hello,

Do you continue to maintain this project ?
I search a simple mariadb operator.

And how I can define the namesapce, ressources request and limits for the pods managed by the operator ?

Regards, 

Thierry.

**Comment by geerlingguy** [comment]
Yes, sorry about that. I'll be working on instructions for use in issue https://github.com/geerlingguy/mariadb-operator/issues/6 — please follow that issue for updates. Thanks!
